---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
#      - PASSWORD=hanxu1987 #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /config:/config
      - /config/workspace:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
